apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: xpaytensorflow
    volumeAttributes:
      containerName: xpaytensorflow
    nodeStageSecretRef:
      name: nfs-secret
      namespace: nfs
    # kubectl create secret generic nfs-secret --from-literal azurestorageaccountname={ACCOUNT_NAME} --from-literal azurestorageaccountkey={ACCOUNT_KEY} --type=Opaque --namespace=kubeflow