apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azureblob-fuse-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: azureblob-fuse-pv
  storageClassName: azureblob-fuse-premium