apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensorboard.fullname" . }}
  labels:
    {{- include "tensorboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "tensorboard.selectorLabels" . | nindent 4 }}